### ISSUE TITLE
频繁遇到错误： telegram.error.BadRequest: Can't parse entities: character '-' is reserved and must be escaped with the preceding '\'

### ISSUE THREAD

**Issue by scavin** [Rongronggg9/RSS-to-Telegram-Bot#1]
> rsstotg_1  | Updating ??????
rsstotg_1  | 	- Pushing https://meta.appinn.net/t/topic/18946
rsstotg_1  | 		- Push https://meta.appinn.net/t/topic/18946 failed!
rsstotg_1  | Traceback (most recent call last):
rsstotg_1  |   File "/app/message.py", line 17, in send
rsstotg_1  |     send_message(chatid, xml, feed_title, url, context)
rsstotg_1  |   File "/app/message.py", line 36, in send_message
rsstotg_1  |     send_media_message(chatid, xml, feed_title, url, pics, context)
rsstotg_1  |   File "/app/message.py", line 121, in send_media_message
rsstotg_1  |     context.bot.send_media_group(chatid, pic_objs)
rsstotg_1  |   File "<decorator-gen-13>", line 2, in send_media_group
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
rsstotg_1  |     result = func(*args, **kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1105, in send_media_group
rsstotg_1  |     result = self._request.post(url, data, timeout=timeout)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 328, in post
rsstotg_1  |     result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
rsstotg_1  |     raise BadRequest(message)
rsstotg_1  | telegram.error.BadRequest: Can't parse inputmedia: can't parse entities: character '-' is reserved and must be escaped with the preceding '\'
rsstotg_1  | 2020-09-10 09:30:04,789 - JobQueue - ERROR - An uncaught error was raised while executing job rss_monitor
rsstotg_1  | Traceback (most recent call last):
rsstotg_1  |   File "/app/message.py", line 17, in send
rsstotg_1  |     send_message(chatid, xml, feed_title, url, context)
rsstotg_1  |   File "/app/message.py", line 36, in send_message
rsstotg_1  |     send_media_message(chatid, xml, feed_title, url, pics, context)
rsstotg_1  |   File "/app/message.py", line 121, in send_media_message
rsstotg_1  |     context.bot.send_media_group(chatid, pic_objs)
rsstotg_1  |   File "<decorator-gen-13>", line 2, in send_media_group
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
rsstotg_1  |     result = func(*args, **kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1105, in send_media_group
rsstotg_1  |     result = self._request.post(url, data, timeout=timeout)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 328, in post
rsstotg_1  |     result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
rsstotg_1  |     raise BadRequest(message)
rsstotg_1  | telegram.error.BadRequest: Can't parse inputmedia: can't parse entities: character '-' is reserved and must be escaped with the preceding '\'
rsstotg_1  |
rsstotg_1  | During handling of the above exception, another exception occurred:
rsstotg_1  |
rsstotg_1  | Traceback (most recent call last):
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 418, in tick
rsstotg_1  |     job.run(self._dispatcher)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 574, in run
rsstotg_1  |     self.callback(CallbackContext.from_job(self, dispatcher))
rsstotg_1  |   File "telegramRSSbot.py", line 157, in rss_monitor
rsstotg_1  |     message.send(chatid, entry['summary'], rss_d.feed.title, entry['link'], context)
rsstotg_1  |   File "/app/message.py", line 23, in send
rsstotg_1  |     traceback.format_exc().replace('\n', '<br>'), feed_title, url, context)
rsstotg_1  |   File "/app/message.py", line 39, in send_message
rsstotg_1  |     send_text_message(chatid, xml, feed_title, url, False, context)
rsstotg_1  |   File "/app/message.py", line 103, in send_text_message
rsstotg_1  |     context.bot.send_message(chatid, head + text_list[i], parse_mode='MarkdownV2', disable_web_page_preview=True)
rsstotg_1  |   File "<decorator-gen-2>", line 2, in send_message
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
rsstotg_1  |     result = func(*args, **kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 348, in send_message
rsstotg_1  |     timeout=timeout, **kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 175, in _message
rsstotg_1  |     result = self._request.post(url, data, timeout=timeout)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
rsstotg_1  |     **urlopen_kwargs)
rsstotg_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 244, in _request_wrapper
rsstotg_1  |     raise BadRequest(message)
rsstotg_1  | telegram.error.BadRequest: Can't parse entities: character '-' is reserved and must be escaped with the preceding '\'

通过 Docker 安装。

**Comment by Rongronggg9** [comment]
实在是不好意思，现在才看到 issue 。
已经在 a0eedf7 中修复，烦请测试后反馈一下结果。

<details>
这个问题的出现是由于 RSS 源的标题中存在 `-` ，而给消息编码时，最后的 `via [feed_title](post_url)` 不会经过转义处理流程，导致标题中含有任何需转义字符即引起错误，这是我的疏忽。
</details>

**Comment by Rongronggg9** [comment]
ef65846
我再进一步测试了一下您的 RSS feed (没找错的话应该是 https://meta.appinn.net/latest.rss )，发现它的格式实在是太杂乱了，甚至都有点不太像 RSS 了，我尽力做了适配，您再测试一下吧。

RSSHub 输出的微博 RSS feed 确实是几乎没有格式的，经过这次适配也许本 bot 可以用于更多格式丰富的 RSS feed 了。
**然 Telegram 消息的格式支持并不够，需要被迫丢掉许多格式，需要保留格式的，我还是推荐使用 [indes/flowerss-bot](https://github.com/indes/flowerss-bot)** 。(注意作者提供的 bot 已不可用，需要自己搭建，作者的 Docker Hub repo 也远落后于 GitHub，需要自己想办法)

![image](https://user-images.githubusercontent.com/15956627/94775247-0cffed00-03f2-11eb-85b9-d289770c2d7a.png)
