### ISSUE TITLE
I cannot subcribe to politepol.com rss

### ISSUE THREAD

**Issue by Launacloud** [Rongronggg9/RSS-to-Telegram-Bot#135]
/sub https://politepol.com/fd/](https://politepol.com/fd/***********

Failed to subscribe
https://politepol.com/fd/*********** (ERROR: Network error (ClientConnectorError))

**Comment by Rongronggg9** [comment]
Self-hosted or public demo?

**Comment by Launacloud** [comment]
Self-hosted I"m using heroku. I tried some others feeds generated by politepol and the same happens I can sub them in tiny tiny rss and miniflux

**Comment by Launacloud** [comment]
I tried in the public demo and it worked... 
I deployed the dev version and it worked, sorry about that.
