### ISSUE TITLE
微博视频无法正确展示

### ISSUE THREAD

**Issue by grinor** [Rongronggg9/RSS-to-Telegram-Bot#147]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/39542317/185728830-42c6db9c-719a-4f87-bbd1-807e7d3bf654.png">

你好，使用最新版的rsshub生成的微博源无法正确展示视频，显示为invalid video，在境内自建freshrss阅读器中展示正常，希望修复该问题，非常感谢！

**Comment by Rongronggg9** [comment]
I am not very sure why this would happen, but please note that:

> 微博会针对请求的来源地区返回不同的结果。
> 一个已知的例子为：部分视频因未知原因仅限中国大陆境内访问 (CDN 域名为 `locallimit.us.sinaimg.cn` 而非 `f.video.weibocdn.com`)。若一条微博含有这种视频且 RSSHub 实例部署在境外，抓取到的微博可能不含视频。将 RSSHub 部署在境内有助于抓取这种视频，但阅读器也必须处于境内网络环境以加载视频。

If your RSStT instance is not deployed in Mainland China, the limited CDN (`locallimit.us.sinaimg.cn`) will just return an HTTP 403, refusing to return the video.

https://github.com/DIYgod/RSSHub/blob/f78ad0319e16a922f08887303cc90ce8787dafe7/docs/social-media.md?plain=1#L1292-L1293
