### ISSUE TITLE
how unsub in chat?

### ISSUE THREAD

**Issue by bazir123** [Rongronggg9/RSS-to-Telegram-Bot#150]
how unsub from feed?
i put bellow command 
/unsub @username
in private chat that i am in with bot only
return this
This command can only be used in a private chat.

how solve this?

**Comment by Rongronggg9** [comment]
@bazir123 If you want to unsubscribe from subscriptions in the current chat, just /unsub, no @username.

**Comment by bazir123** [comment]
i send message bot replay
The bot is no longer in this group/channel, thus won't work here.

**Comment by bazir123** [comment]
because there  a lot feed and 
when i send /unsub  it show just like 100 page 
i removed bot from private group  and  re_added still same

**Comment by bazir123** [comment]
ok got it how to do it

**Comment by bazir123** [comment]
just need /unsub url1  url2
thanks for great tool
