### ISSUE TITLE
Posts are not in the correct order

### ISSUE THREAD

**Issue by sepehrbrj** [Rongronggg9/RSS-to-Telegram-Bot#157]
**Describe the bug**
Posts are not in the correct order as in the source feed.

<details><summary>Screenshots</summary>

Feed posts:
![Screenshot_20220907-150047_1](https://user-images.githubusercontent.com/55192376/188955556-41394a96-5b9b-4735-bfcb-7f652cd4dba6.png)

Bot posts:
![Screenshot_20220907-145940_1](https://user-images.githubusercontent.com/55192376/188955592-fd83f56c-3059-4c95-a367-d5a10263f682.png)
</details>

**Comment by Rongronggg9** [comment]
This is not a bug.
Given that the bot is asynchronous and performance-optimized, each new post within each updated feed creates a "task", then all tasks are handled asynchronously (or, to make it easier, concurrently). Asynchronous means that the order of tasks to finish is uncertain. Also, each task is context-free, so it itself can never know whether other tasks are finished or not.

**Comment by sepehr-brj** [comment]
At first, I also thought this issue was inevitable, but some other bots don't have this issue.

I don't know about the RSStT bot function and just reported the issue.
If this issue is fixed, it'd great. If not, no problem.

**Comment by Rongronggg9** [comment]
I will have this issue kept open. If someday the "sending post" tasks are contextual, it is possible to send posts in order. But before that, #122 needs to be implemented.
