### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by ulysses4ever** [Rongronggg9/RSS-to-Telegram-Bot#160]
Would it be possible to add support for Atom feeds along with RSS ones? That would be extremely useful, and it shouldn't be that much harder, hopefully.

**Comment by Rongronggg9** [comment]
Atom has been supported since the project was born. Did you face any problem subscribing to Atom feeds?

**Comment by ulysses4ever** [comment]
Hm, interesting. I tried `/sub https://github.com/Rongronggg9/RSS-to-Telegram-Bot/commits/master.atom` but the bot didn't respond anyhow. Do you have an idea why?

**Comment by Rongronggg9** [comment]
OK then, it seems that Telegram DC had some internal error and stopped sending messages to the demo bot. I've restarted it and everything should be fine now.

**Comment by ulysses4ever** [comment]
It does work now, thank you!
