### ISSUE TITLE
Import opml leads to "Reply with file" being presented

### ISSUE THREAD

**Issue by marcin93** [Rongronggg9/RSS-to-Telegram-Bot#170]
**Describe the bug**
Once used bulk subscription upload I'm getteing "Reply with file..." being presented on mobile and desktop client. Did that with 2 instances: Heroku & VM + docker - same effect. That lead to situation when once going to chat I'm being moved to bottom of chat instead of head of "Unread".

**To Reproduce**
1. launch dockerized instance
2. use /import
3. upload *.opml
4. See error: now and then, you will see on all devices message "Reply with file..." on client which initiated action and other (desktop/mobile)

**Expected behavior**
Once replied with file, message to reply don't appear any more.

**Comment by Rongronggg9** [comment]
c166bccf368799bf18d48505432ce7e3faaf06d5

```
fix(`/import`): ForceReply not cleared

This is not a perfect fix. Telegram does not allow clearing
ReplyKeyboardForceReply w/o sending a message w/ ReplyKeyboardHide, but
such a message cannot be edited, making anything in a dilemma. A
possible workaround is to delete the message itself, so that nothing can
be force-replied. That's exactly what the commit does.
```
