### ISSUE TITLE
Not sending the post or updating 

### ISSUE THREAD

**Issue by louanfontenele** [Rongronggg9/RSS-to-Telegram-Bot#186]
2022-10-13-17:37:00:INFO:RSStT.monitor - Monitoring tasks summary in last 10 minutes: updated(0), not updated(5, including 0 cached and 0 empty), fetch failed(0), skipped(5), timeout(0)

I dont know why, but for example, im using a rss feed to get new videos from a youtube channel, even the someone posts a video, the rss feed do not send to the channels, and i already set /sub xml to youtube channel, but even this, do not work. please someone help me.

**Comment by louanfontenele** [comment]
@louanfontenele Only when I restart the server the posts are sent to channels

**Comment by Rongronggg9** [comment]
more logs needed, set `DEBUG=1`

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/advanced-settings.md#misc-settings
