### ISSUE TITLE
discontinuing heroku

### ISSUE THREAD

**Issue by bazir123** [Rongronggg9/RSS-to-Telegram-Bot#199]
hello
since heroku closing can make it run on github action?
i am not program just asking

**Comment by Rongronggg9** [comment]
It is impossible to host RSStT on GHA.

To host RSStT, certain requirements must be met:
1. ~0 downtime (GHA: [each job can only last for 6 hours](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits))
2. persistent PostgreSQL database, or persistent storage to be used by SQLite (GHA: none)

The only PaaS platform meeting the requirements is [Railway.app](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/deployment-guide.md#option-2-railwayapp).
