### ISSUE TITLE
The monitor interval must be greater than 5 minutes.

### ISSUE THREAD

**Issue by ItIsSeven** [Rongronggg9/RSS-to-Telegram-Bot#201]
Hello I want the RSS feed to update every 1min, but that's not possible because of this error.
I'm hosting using Docker, is there any way I can circumvent this?

**Comment by sekai233** [comment]
`/set_option minimal_interval 1`
Send this command above to change the minimum interval

**Comment by ItIsSeven** [comment]
Ah right okay, thanks that worked perfectly. Is it possible to do 30 seconds or less aswell?
Thanks.

**Comment by sekai233** [comment]
> Ah right okay, thanks that worked perfectly. Is it possible to do 30 seconds or less aswell? Thanks.

The minimum time interval for crontab is 1 minute
Lower intervals need to be achieved in other ways

For rss 1 minute is enough to use

**Comment by ItIsSeven** [comment]
Ah right that makes sense thanks, I needed it to be as low as possible.
