### ISSUE TITLE
Feature Request: Blacklist certain words/strings from appearing in the feed

### ISSUE THREAD

**Issue by ItIsSeven** [Rongronggg9/RSS-to-Telegram-Bot#202]
This will be a very useful feature as a lot of the time with RSS feeds, there's a lot of noise, with a lot of news that isn't relevant.
So if we could blacklist certain words/strings from appearing in the feed that would be an extremely useful feature.

**Comment by sekai233** [comment]
https://github.com/Rongronggg9/RSS-to-Telegram-Bot/issues/159#issuecomment-1244770907

**Comment by ItIsSeven** [comment]
I've replied in that issue instead now.
