### ISSUE TITLE
Self-hosted Telegram API Support

### ISSUE THREAD

**Issue by patschi** [Rongronggg9/RSS-to-Telegram-Bot#207]
I'd like to see support for the self-hosted Telegram API server available over here: https://github.com/tdlib/telegram-bot-api. That offers some quite neat advantages instead of `api.telegram.org`, especially when having multiple bots hosted on same infrastructure.

**Comment by Rongronggg9** [comment]
https://github.com/Rongronggg9/RSS-to-Telegram-Bot/issues/191#issuecomment-1291721281

**Comment by Rongronggg9** [comment]
> especially when having multiple bots hosted on same infrastructure.

Using MTProto API, there shouldn't be a lot of overhead if multiple instances are hosted on the same infrastructure unless your network environment is awful.

Some features depend on MTProto API since HTTP API simply never provides them, so it is unlikely possible to support HTTP API.
