### ISSUE TITLE
Since december 16 posts from reddit rss have wrong links

### ISSUE THREAD

**Issue by soredake** [Rongronggg9/RSS-to-Telegram-Bot#219]
**Describe the bug**
Since december 16 posts from reddit rss have wrong links, all /u/, [link] and [comments] links are wrong, they all point to https://www.reddit.com/r/<subreddit>/.rss
![изображение](https://user-images.githubusercontent.com/5204968/208127796-0b9352ad-bd46-44dd-85e5-6ea41061e89a.png)

**To Reproduce**
1. Subscribe to https://www.reddit.com/r/FreeGameFindings/.rss in bot
2. Wait for posts.
3. Links will be wrong.

**Expected behavior**
Have correct links.

**Important log**
You may execute `docker logs [container name]` to get log.
Choose that is important and paste it here.

**Comment by Rongronggg9** [comment]
The public demo has been upgraded.
