### ISSUE TITLE
Make the bot "private" [feature request]

### ISSUE THREAD

**Issue by ippocratis** [Rongronggg9/RSS-to-Telegram-Bot#234]
Telegram bots are public by default. 
Everyone that knows the bot name can contact the bot and start a chat with it. 
It would make sense for those self hosting the bot for personal use to have a feature that makes the bot respond only to it's "creator"

Btw
Thanks for the great project and keep up

**Comment by Rongronggg9** [comment]
https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/FAQ.md#q-i-want-my-bot-to-serve-me-only-what-should-i-do

**Comment by ippocratis** [comment]
Already covered
nice
Sorry  I rushed to open an issue 
Keep up
