### ISSUE TITLE
[Feature Request] 将更多的指令允许为远程执行与支持部分指令全局执行

### ISSUE THREAD

**Issue by cxplay** [Rongronggg9/RSS-to-Telegram-Bot#264]
在频道中使用 bot 还需要将频道 ID 添加为用户，并且一旦添加频道 ID 为用户之后，所有可在频道发言的成员都等于拥有了权限。由此，如果需要使用 `/lang` 指令初始化一个频道中的机器人界面语言就需要在频道中发送 `/lang` 指令才能进入面板设置；

再者 `/test` 指令是一个很好的预览 feed 格式化输出效果的方法，但是无法进行远程执行，并且由于该指令目前仅限管理员执行，所以由开头提到的频道身份问题，即使 bot 管理员在频道中使用 `/test` 指令也会提示权限不足.

所以，如果有可能做到支持，希望将 `/lang` 和 `/test` 指令设置为支持远程执行.

---

此外，对于对多用户管理，建议部分指令可在管理员进行远程执行时支持附加参数实现全局执行 (即对所有用户生效), 如 `/set_default`, `/lang`, `/set_sub_limit`.

**Comment by Rongronggg9** [comment]
> 所以，如果有可能做到支持，希望将 `/lang` 和 `/test` 指令设置为支持远程执行.

Fixed in 90d4745

> 此外，对于对多用户管理，建议部分指令可在管理员进行远程执行时支持附加参数实现全局执行 (即对所有用户生效), 如 `/set_default`, `/lang`, `/set_sub_limit`.

具有侵入性，且需要大幅更新数据库 schema，不容易实现，未有计划。
