### ISSUE TITLE
OPML file compatibility

### ISSUE THREAD

**Issue by vlmarch** [Rongronggg9/RSS-to-Telegram-Bot#270]
**Describe the bug**
feedly.com sees the exported OPML file as empty. Thunderbird Feed Account imports each subscription as a folder (without the feed).

**To Reproduce**
Steps to reproduce the feedly.com behavior:
1. Export subscriptions using `/export`.
2. According to the ["New OPML Import"](https://blog.feedly.com/opml/) instructions I tried to import the exported file.
3. The file was not imported. `Error : Empty OPML file`

Steps to reproduce the Thunderbird behavior:
1. Export subscriptions using `/export`.
2. In the Feed Account settings in Thunderbird. I switched to `Manage Subscriptions...` and selected `Import`.
4. After importing the file, folders appeared that represents individual subscriptions (without the feed).
 
**Expected behavior**
In both cases I wanted to import subscriptions.

**Solution**
Currently, `outline` subscriptions look like this:
```xml
<outline text="Graham Cluley" xmlUrl="http://feeds.feedburner.com/GrahamCluleysBlog">
</outline>
```
I edited the definitions of the individual subscriptions to the state as below and the file was correctly imported into feedly and Thunderbird. 
```xml
<outline type="rss" text="Graham Cluley" xmlUrl="http://feeds.feedburner.com/GrahamCluleysBlog"/>
```

**Another suggestion**
It would be nice if when importing, all subscriptions from "RSS to Telegram Bot" would fall into one group (e.g. "RSS to Telegram Bot"). The `body` structure below would provide such grouping.
```xml
<body>
    <outline text="RSS to Telegram Bot" title="RSS to Telegram Bot">
        <outline ..../>
        <outline ..../>
        <outline ..../>
        ....
        <outline ..../>
    </outline>
</body>
```

**Comment by Rongronggg9** [comment]
> Solution

I've applied your solution in 67baf0bd41c7a9a07b10b4a73508872f61595aa5. Could you test if it works properly?

> Another suggestion

OPML is a specification that is too elastic. I am not sure if your suggestion will lead to undesired effects in some RSS readers. Also, as RSStT supports adding hashtags to a subscription, it can be exported too in the future. Your suggestion may somehow conflict with that.
