### ISSUE TITLE
订阅微博用户提示订阅失败

### ISSUE THREAD

**Issue by huangyongde** [Rongronggg9/RSS-to-Telegram-Bot#274]
版本信息：v2.2.1-365-g0b9b8e7@dev
build@2023-04-18T13:07:49+00:00
操作：
/sub https://weibo.com/u/xxxx(标识用户id)

错误提示：
<img width="471" alt="image" src="https://user-images.githubusercontent.com/40013727/233829304-21f033fe-53ca-4643-9db3-88f8ac9a6835.png">

**Comment by Rongronggg9** [comment]
https://zh.wikipedia.org/wiki/RSS

**Comment by huangyongde** [comment]
> it's my mistake. Can't subscribe to the Weibo address directly. I need to convert it to an RSS feed first. I pasted the wrong address.
