### ISSUE TITLE
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: TOPIC_CLOSED (caused by SendMediaRequest)

### ISSUE THREAD

**Issue by Jv0id** [Rongronggg9/RSS-to-Telegram-Bot#275]
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: TOPIC_CLOSED (caused by SendMediaRequest)
stderr: [31m2023-04-23-15:42:07:ERROR:RSStT.monitor - Failed to send https://twitter.com/TheEngineering_/status/1650016766997966849 (feed: https://rss-bridge.org/bridge01/?action=display&bridge=TwitterBridge&context=By+username&u=cctv1008&format=Atom, user: -1001943633930):[0m
stderr: Traceback (most recent call last):
stderr:   File "/app/src/command/monitor.py", line 295, in __send
stderr:     await post.send_formatted_post_according_to_sub(sub)
stderr:   File "/app/src/parsing/post.py", line 54, in send_formatted_post_according_to_sub
stderr:     await self.send_formatted_post(
stderr:   File "/app/src/parsing/post.py", line 125, in send_formatted_post
stderr:     return await message_dispatcher.send_messages()
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/app/src/parsing/message.py", line 84, in send_messages
stderr:     msg = await message.send(reply_to=sent_msgs[-1] if sent_msgs else None)
stderr:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/app/src/parsing/message.py", line 153, in send
stderr:     result = await env.bot(request)
stderr:              ^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/opt/venv/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
stderr:     return await self._call(self._sender, request, ordered=ordered)
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/opt/venv/lib/python3.11/site-packages/telethon/client/users.py", line 84, in _call
stderr:     result = await future
stderr:              ^^^^^^^^^^^^
stderr: telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: TOPIC_CLOSED (caused by SendMultiMediaRequest)
stderr: [31m2023-04-23-15:42:08:ERROR:RSStT.parsing - Failed to send post to user -1001798129968 (feed: https://rss-brid

报以上错误，bot不是我使用的，只是我搭建的。而且只有一个订阅源有这个问题。

**Comment by cxplay** [comment]
我的机器人测试正常

![image](https://user-images.githubusercontent.com/62034099/233914733-632d306c-1852-4892-bbf4-3a7ea4a243f5.png)

**Comment by Jv0id** [comment]
其实我自己测试也是没有问题的，但是不清楚为什么bot会报错，后台日志也报错。
<img width="636" alt="image" src="https://user-images.githubusercontent.com/35218851/233917084-95085228-dba0-454d-af0c-2b4d8c115d1e.png">

实在不行我就把bot改成私人的吧。

**Comment by Rongronggg9** [comment]
目前对开启 topic 的群组的支持尚不完善，订阅永远发送至 general topic。如果 general topic 被关闭就会出现这个错误。目前还没有对这个错误进行特别的处理。

See also #246

**Comment by Jv0id** [comment]
> 目前对开启 topic 的群组的支持尚不完善，订阅永远发送至 general topic。如果 general topic 被关闭就会出现这个错误。目前还没有对这个错误进行特别的处理。
> 
> See also #246

难怪，他使用的就是在开启topic的群组了。受教了，感谢🙏
