### ISSUE TITLE
[Feature Request] Send latest article

### ISSUE THREAD

**Issue by Bamboozul** [Rongronggg9/RSS-to-Telegram-Bot#276]
Could you add this command so that we can preview the customization on the message before applying it?

Note: I'm using the public bot for now.

**Comment by Rongronggg9** [comment]
Deploy your own bot and `/test` after customizing a subscription. The command can only be used by the bot manager (or, owner). In order to protect the bot from DoS attack, there is no plan to make ordinary users able to use the command.

**Comment by Bamboozul** [comment]
> Deploy your own bot and `/test` after customizing a subscription. The command can only be used by the bot manager (or, owner). In order to protect the bot from DoS attack, there is no plan to make ordinary users able to use the command.

fair enough.
