### ISSUE TITLE
Feature Request: 加入对gif的支持

### ISSUE THREAD

**Issue by aisuneko** [Rongronggg9/RSS-to-Telegram-Bot#3]
(当然不知道是rsshub就不支持gif还是bot没有实现)

**Comment by Rongronggg9** [comment]
由于 Telegram Bot API 限制，无法在 media group 内包含 gif ，只能每张 gif 单独占用一条消息发送。
一个可行的方法是把 gif 转换成有音轨的 mp4 (无音轨 mp4 在 Telegram 看来等同于 gif)，这样就能作为视频包含入 media group 。
有机会再做这个实现。

Parameter | Type | Required | Description
-- | -- | -- | --
chat_id | Integer or String | Yes | Unique identifier for the target chat or username of the target channel (in the format @channelusername)
media | **Array of InputMediaPhoto and InputMediaVideo** | Yes | A JSON-serialized array describing photos and videos to be sent, must include 2-10 items
disable_notification | Boolean | Optional | Sends the messages silently. Users will receive a notification with no sound.
reply_to_message_id | Integer | Optional | If the messages are a reply, ID of the original message

https://core.telegram.org/bots/api#sendmediagroup

**Comment by Rongronggg9** [comment]
dev 分支以 GIF 消息单独发送的形式实现了这个 feature。
应当不会再考虑转换为有声轨视频的做法，因为这过于消耗流量和资源。

**Comment by Rongronggg9** [comment]
已进入 master 分支。
