### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by DevilStyle** [Rongronggg9/RSS-to-Telegram-Bot#319]
Hello congratulations for your project, I wanted to ask you if it is possible to make the bot use only one person instead of all people. A thousand thanks

**Comment by Rongronggg9** [comment]
https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/FAQ.md#q-i-want-my-bot-to-serve-me-only-what-should-i-do

**Comment by DevilStyle** [comment]
Thank you very much for the reply it worked. Thanks again
