### ISSUE TITLE
large pictures are cropped

### ISSUE THREAD

**Issue by of-me-is** [Rongronggg9/RSS-to-Telegram-Bot#329]
**Describe the bug**
pictures that are long are cropped (for example, 650x5300 is cropped to 650x1200) when received through this telegram bot and this rss https://github.com/zgq354/weibo-rss

**To Reproduce**
1. use rss for any blog that posts large pictures (for example, web comics)
2. click on the picture in the chat, see that it's cropped

**Expected behavior**
a full-size picture, or the link to it if the full-size embed isn't available. although telegram does support long pictures, so it's weird that they get cropped. the links in the rss lead to full-size images.

**Comment by Rongronggg9** [comment]
Weird. Could you dump the RSS feed, upload it, and tell me which picture was cropped?

**Comment by of-me-is** [comment]
not sure what you mean by dump, but here's he link to the rss: https://rss.smallmaple.com/rss/user/1862364383

all the pictures which have "large" in the name are cropped every time

**Comment by Rongronggg9** [comment]
Reproduced, I will investigate it.
