### ISSUE TITLE
自建图床无法被wsrv.nl解析

### ISSUE THREAD

**Issue by VCE1** [Rongronggg9/RSS-to-Telegram-Bot#369]
一些博客会使用一些自建的图床，而[wsrv.nl](wsrv.nl)屏蔽了包括 .cc .club .date .fun .pw .top .xxx .xyz 等域名。
https://github.com/weserv/images/issues/339#issuecomment-1096952128
请问该如何解决呢？

**Comment by VCE1** [comment]
目前看来只能自行更换域名解决。

**Comment by Rongronggg9** [comment]
你可以自行搭建 weserv

**Comment by Rongronggg9** [comment]
Reopen as the issue can be worked around by using image relay
