### ISSUE TITLE
How to send webp images as webp instead of png?

### ISSUE THREAD

**Issue by BlackYuzia** [Rongronggg9/RSS-to-Telegram-Bot#372]
Hello there.

I have rss feed with images. But, when I send images (**webp**) and when bot send images, we get different results.

UPD: I found what telegram client could send webp format, but bot send webp as png. This could be fixed?

[png_example ](https://fastdl.starserv.net/test1234/vue-router.png)| [webp_example ](https://fastdl.starserv.net/vue-router-b.webp) (diff colors)

BOT (as png):
![image](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/25010528/ff04fd8b-60cf-4353-8e49-68561154ea0a)

ME (as webp):
![image](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/25010528/d95498cb-77e3-40da-9de6-cecf2da7fea0)

**Comment by Rongronggg9** [comment]
> telegram client could send webp format

Another fact is that some clients treat webp as a sticker, resulting in the caption being hidden. That's why RSStT converts all webp images into png before sending them. It is https://wsrv.nl/ that does the conversion. But https://wsrv.nl/?url=fastdl.starserv.net/vue-router-b.webp&output=png seems fine, at least in Firefox. 🤔

**Comment by BlackYuzia** [comment]
> > telegram client could send webp format
> 
> Another fact is that some clients treat webp as a sticker, resulting in the caption being hidden. That's why RSStT converts all webp images into png before sending them. It is https://wsrv.nl/ that does the conversion. But https://wsrv.nl/?url=fastdl.starserv.net/vue-router-b.webp&output=png seems fine, at least in Firefox. 🤔

idk why it happen, but how I wrote above, bot image lost colors.
However, currently I fix this by using png (8) instead of webp.

**Comment by Rongronggg9** [comment]
Oh, I've forgotten the commit: https://github.com/Rongronggg9/RSS-to-Telegram-Bot/commit/3bafebf781b9705738dcf9380b0e1659e5eb5283

So it turns out that Telegram cannot properly convert webp. I will revert the commit. Thanks for your bug report!
