### ISSUE TITLE
Video is too big

### ISSUE THREAD

**Issue by vppower-wqr** [Rongronggg9/RSS-to-Telegram-Bot#373]
My RSSTT bot running from my local telegram bot api server, but when I received from another telegram sources to my bot, and they have video over 50Mb. I got "Video is to big" How can I fix this? Thanks

**Comment by Rongronggg9** [comment]
> My RSSTT bot running from my local telegram bot api server

RSStT does not use HTTP bot API, thus it would never use your local API server.
The limitation happens on Telegram servers.

**Comment by vppower-wqr** [comment]
Any chance to change this limitation? Or maybe other way? Maybe you can make for local server? Appreciate you work, hope you continue supporting this project)

**Comment by Rongronggg9** [comment]
> Any chance to change this limitation? Or maybe other way?

No, but I am not sure if the server-side limitation has changed these years.

> Maybe you can make for local server?

I repeat, that RSStT does NOT use HTTP bot API. Any "local server" is actually a local HTTP bot API server. RSStT depends heavily on the MTProto API which provides much more features than the HTTP one. Thus it is impossible to support HTTP bot API.
