### ISSUE TITLE
Bot 链接解析时进行了编码导致无法访问

### ISSUE THREAD

**Issue by Ovler-Young** [Rongronggg9/RSS-to-Telegram-Bot#402]
**Describe the bug**
我正在使用自建的RSS-to-Telegram-Bot进行订阅,版本为
```
v2.5.0@dev, build@2024-01-09T18:40:45+00:00
```
在利用`RSSHub`订阅歌手歌曲更新时,发现解析后的音乐链接被错误编码,导致无法访问。

**To Reproduce**
1. 订阅 `https://rsshub.app/163/music/artist/songs/11975111` 或者其他音乐人，接到推送后发出消息，或者 `/test  https://rsshub.app/163/music/artist/songs/11975111`
2. 点击消息中 `Via` 后的链接
3. 网易云音乐无法正确加载

**Expected behavior**
Via链接正确的加载

**Important log**
和这条相关的item如下：

``` xml
<item>
<title>
<![CDATA[ 白鸟过河滩 - ilem ]]>
</title>
<description>
<![CDATA[ 歌手：ilem<br>专辑：白鸟过河滩<br> <img src="https://p2.music.126.net/4bj6mYcfRc8TXcXPJS7N4g==/109951169244585744.jpg" referrerpolicy="no-referrer"> ]]>
</description>
<guid isPermaLink="false">https://music.163.com/#/song?id=2115520005</guid>
<link>https://music.163.com/#/song?id=2115520005</link>
</item>
```

正确的链接为` https://music.163.com/#/song?id=2115520005`
进行了urlencode后为 `https://music.163.com/#%2Fsong%3Fid%3D2115520005`

**其他**

进行encode时似乎只对后随的/进行了处理?

**Comment by Ovler-Young** [comment]
参考的消息转发到了telegram讨论组，链接为 https://t.me/RSStT_Group/10228

**Comment by Rongronggg9** [comment]
Upstream (https://github.com/niksite/url-normalize) bug. Will replace it.

**Comment by Rongronggg9** [comment]
31f62069
