### ISSUE TITLE
Batch arrival 

### ISSUE THREAD

**Issue by parduspanteri** [Rongronggg9/RSS-to-Telegram-Bot#405]
Membership posts published at different times sometimes arrival in batches a few hours later.

**Comment by Rongronggg9** [comment]
Feed URL?

**Comment by Rongronggg9** [comment]
Nitter will "cache" Twitter API responses and will not make further API requests to fetch the newest posts before cache expiration. That's the root cause of the "delay" and "batch arrival" you've seen.
