### ISSUE TITLE
multi manager possible?

### ISSUE THREAD

**Issue by ristein** [Rongronggg9/RSS-to-Telegram-Bot#411]
Hey,
thank you for this great tool.
Is it possible to have multiple managers?
I just copy-pasted that line in compose file but it does not seem to work.
Would be great if a friend of mine wanted to add users to not have to tell me to.
Best regards

**Comment by Rongronggg9** [comment]
@ristein Possible. In plan.

**Comment by Rongronggg9** [comment]
106226261fbb680426d59444e9a2e78798185d1f

**Comment by ristein** [comment]
this does not work anymore. as soon as there are two managers defined, I can't even use list command in private chat with my bot. It says "You don't have permission to use this command.".
Removing second manager and restarting solves this.
I tried with and without quotes, space, semicolon and comma

**Comment by Rongronggg9** [comment]
`/version`?

**Comment by ristein** [comment]
v2.5.0@master
build@2024-01-09T18:41:03+00:00

**Comment by Rongronggg9** [comment]
The feature has not entered any releases. Use `dev` branch instead.

**Comment by ristein** [comment]
oops, my fault
