### ISSUE TITLE
如何在群组或频道内使用

### ISSUE THREAD

**Issue by mucstudio** [Rongronggg9/RSS-to-Telegram-Bot#43]
请问下大佬，如何在频道或者群组使用

/sub @群组 rss链

没用

**Comment by Rongronggg9** [comment]
> ### **Q**: 如何在频道或群组里使用 bot ？
>
> **A**: 将 bot 添加到你的频道或群组里，然后发送命令就可以了。在频道里，需要「发送消息」权限。而如果你是群组的匿名管理员，bot 也需要成为管理员（不需要任何权限）才能验证你的身份。

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/master/docs/FAQ.zh.md

直接在群组或频道里发送命令。

**Comment by abolast** [comment]
群里或者频道并不会出现 / 命令，所以直接发送**文字** /sub url url1 url2 即可，还能发送 /list 来查看自己订阅了什么 ，还能用 /unsub url来取消某个订阅
