### ISSUE TITLE
Webp 图片导致文本内容消失

### ISSUE THREAD

**Issue by codehz** [Rongronggg9/RSS-to-Telegram-Bot#45]
**Describe the bug**
多数 Telegram 客户端会把 webp 图片当作贴纸看待，而贴纸是没有文本内容的（实际用API可提取文本内容）

**To Reproduce**
1. 找一个能提供（内容中包含）webp图片的rss源
2. 机器人上点订阅
3. 然后看推送就会发现文本内容消失了

**Expected behavior**
将webp图片转换成其他任意格式

**Important log**
这应该属于Telegram客户端渲染的问题，服务端应该不会收到任意错误信息，因此也无法提供有意义的日志

**Comment by Rongronggg9** [comment]
19d2685

请测试后反馈

**Comment by codehz** [comment]
看起来后缀为webp的确实正常了
但是有些迷惑站用的cdn（大概？）会用jpg后缀发webp内容，（虽然我遇到的这种站点没rss支持，而且测试cdn也会按照ua判断发送格式），不过可以认为没啥问题了

**Comment by Rongronggg9** [comment]
> 但是有些迷惑站用的cdn（大概？）会用jpg后缀发webp内容，（虽然我遇到的这种站点没rss支持，而且测试cdn也会按照ua判断发送格式），不过可以认为没啥问题了

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/src/parsing/medium.py#L241-L247

最终由响应头来判断。
