### ISSUE TITLE
Reddit RSS Image Fail Invalid media: image 

### ISSUE THREAD

**Issue by weskerty** [Rongronggg9/RSS-to-Telegram-Bot#465]
## Describe the bug
The bot cannot rescue reddit images, it shows the error "Invalid media: image"
Previously it was shown.
Entering the mentioned image shows a common image in the browser.

## To Reproduce
1 Add reddit.com/user/?????/.rss
Bot Only Images and User.

> [!TIP]\
> reddit.com/user/?????/.rss

## Expected behavior
Previously I sent the images to the telegram chat

## Important log
> [!IMPORTANT]\
> retrying: https://wsrv.nl/?url=https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640%26crop=smart%26auto=webp%26s=22de2871e95a600b75015d88212f3fd7c7e57def&w=2560&h=2560&output=jpg&q=89&we=1                                                       2024-05-26-12:14:01:DEBUG:RSStT.web - Medium fetch failed: https://wsrv.nl/?url=https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640%26crop=smart%26auto=webp%26s=22de2871e95a600b75015d88212f3fd7c7e57def&w=2560&h=2560&output=jpg&q=89&we=1           Traceback (most recent call last):                              File "/root/rsstt/src/web/req.py", line 159, in fetch          async with session.request(                                 File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 1197, in __aenter_                                     self.resp = await self._coro                               File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 581, in _request                                        conn = await self._connector.connect(                       File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 544, in connect                                      proto = await self._create_connection(req, traces, timeout)                                                               File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 944, in _create_connection                           _, proto = await self._create_direct_connection(req, traces, timeout)                                                     File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection                   transp, proto = await self._wrap_create_connection(         File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection                     return await self._loop.create_connection(*args, **kwargs)  File "uvloop/loop.pyx", line 2029, in create_connection       File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection                                                  asyncio.exceptions.CancelledError                                                                                           During handling of the above exception, another exception occurred:                                                                                                                       Traceback (most recent call last):                              File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for                                                             fut.result()                                              asyncio.exceptions.CancelledError                                                                                           The above exception was the direct cause of the following exception:                                                                                                                      Traceback (most recent call last):                              File "/root/rsstt/src/web/media.py", line 128, in get_medium_info                                                             r = await _get(url, resp_callback=medium_info_callback,   File "/root/rsstt/src/web/req.py", line 219, in _request        raise e                                                     File "/root/rsstt/src/web/req.py", line 206, in _request        ret = await asyncio.wait_for(_fetch(), timeout)             File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for                                                             raise exceptions.TimeoutError() from exc                  asyncio.exceptions.TimeoutError                               2024-05-26-12:14:31:DEBUG:RSStT.web - Fetch failed (TimeoutError), retrying: https://wsrv.nl/?url=https://rsstt-img-relay.rongrong.workers.dev/https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640%26crop=smart%26auto=webp%26s=22de2871e95a600b75015d88212f3fd7c7e57def&w=2560&h=2560&output=jpg&q=89&we=1          2024-05-26-12:15:01:DEBUG:RSStT.web - Medium fetch failed: https://wsrv.nl/?url=https://rsstt-img-relay.rongrong.workers.dev/https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640%26crop=smart%26auto=webp%26s=22de2871e95a600b75015d88212f3fd7c7e57def&w=2560&h=2560&output=jpg&q=89&we=1                            Traceback (most recent call last):                              File "/root/rsstt/src/web/req.py", line 159, in _fetch          async with session.request(                                 File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 1197, in __aenter_                                     self.resp = await self._coro                               File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 581, in _request                                        conn = await self._connector.connect(                       File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 544, in connect                                      proto = await self._create_connection(req, traces, timeout)                                                               File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 944, in _create_connection                           _, proto = await self._create_direct_connection(req, traces, timeout)                                                     File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection                   transp, proto = await self._wrap_create_connection(         File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection                     return await self._loop.create_connection(*args, **kwargs)  File "uvloop/loop.pyx", line 2029, in create_connection       File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection                                                  asyncio.exceptions.CancelledError                                                                                           During handling of the above exception, another exception occurred:                                                                                                                       Traceback (most recent call last):                              File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for                                                             fut.result()                                              asyncio.exceptions.CancelledError                                                                                           The above exception was the direct cause of the following exception:                                                                                                                      Traceback (most recent call last):                              File "/root/rsstt/src/web/media.py", line 128, in get_medium_info                                                             r = await _get(url, resp_callback=_medium_info_callback,   File "/root/rsstt/src/web/req.py", line 219, in _request        raise e                                                     File "/root/rsstt/src/web/req.py", line 206, in _request        ret = await asyncio.wait_for(_fetch(), timeout)             File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for                                                             raise exceptions.TimeoutError() from exc                  asyncio.exceptions.TimeoutError                               2024-05-26-12:15:01:DEBUG:RSStT.medium - Dropped medium (file, https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640&crop=smart&auto=webp&s=22de2871e95a600b75015d88212f3fd7c7e57def): both original and relayed image fetch failed                      2024-05-26-12:15:01:DEBUG:RSStT.medium - Dropped medium (image, https://preview.redd.it/e5ino2ltos2d1.jpeg?width=640&crop=smart&auto=webp&s=22de2871e95a600b75015d88212f3fd7c7e57def): both original and relayed image fetch failed, weserv fetch failed2024-05-26-12:15:01:DEBUG:RSStT.monitor - Finished a monitoring task: updated(1), not updated(0, including 0 cached and 0 empty)                                                          2024-05-26-12:16:00:DEBUG:RSStT.monitor - Started a monitoring task.                                                        2024-05-26-12:16:00:DEBUG:RSStT.monitor - Fetched (not updated): https://www.reddit.com/user/dadnothere/.rss                2024-05-26-12:16:00:DEBUG:RSStT.monitor - Finished a monitoring task: updated(0), not updated(1, including 0 cached and 0 empty)

**Comment by Rongronggg9** [comment]
Check your network connection.

**Comment by weskerty** [comment]
> Check your network connection.

I can communicate with the bot and it responds.
Other node bots work fine on the same server. It is a Debian11ARM VPS

**Comment by Rongronggg9** [comment]
The error log already told you:

> both original and relayed image fetch failed, weserv fetch failed

This can only be a network connection issue.

To work around this, try `LAZY_MEDIA_VALIDATION`, `HTTP_TIMEOUT`, `HTTP_CONCURRENCY`, `HTTP_CONCURRENCY_PER_HOST` (refer to https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/advanced-settings.md).

Won't answer any further questions on the issue.
