### ISSUE TITLE
It is possible use cookie tu get some pages?

### ISSUE THREAD

**Issue by onewhitethreee** [Rongronggg9/RSS-to-Telegram-Bot#468]
Hello, 

I want to ask if it's posibble use cookie to get pages, If it can, may I know where to set?

Thank you. 

Best wishes

**Comment by Rongronggg9** [comment]
In the short term, there is no such feature and plan. IMHO if a website verifies cookies before returning RSS feeds, it does harm to the Internet. RSS readers are not necessarily to behave just like a browser, and above all, RSS should be stateless. I've never seen an RSS feed that verifies cookies, and I suspect in your case the RSS feed is just misconfigured.

That being said, I am not opposed to such a feature. PR is welcomed.
