### ISSUE TITLE
Problem with adding two feeds

### ISSUE THREAD

**Issue by ghost** [Rongronggg9/RSS-to-Telegram-Bot#477]
## Describe the bug
The feeds “https://serial.everyeye.it/feed/feed_news_rss.asp” and “https://cinema.everyeye.it/feed/feed_news_rss.asp” are not added to the bot by reporting an error as in the screenshot. The sites whose feeds I extracted are “https://serial.everyeye.it/notizie/” and “https://cinema.everyeye.it/notizie/”

## To Reproduce
Steps to reproduce the behavior.
1. Go to 'bot'
2. Click on '/sub and then the link of the two feeds'
3. See error

## Screenshots
![IMG_2255](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/157696146/af79825f-4de5-43bc-997d-5eec049f9466)

## Feed URL
“https://serial.everyeye.it/feed/feed_news_rss.asp” and “https://cinema.everyeye.it/feed/feed_news_rss.asp”

**Comment by Rongronggg9** [comment]
Self-host bot works well. The public demo is expected to receive HTTP 403/429. Please deploy a self-host bot in such a circumstance.
