### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by purk4** [Rongronggg9/RSS-to-Telegram-Bot#48]
Please advice, I installed the script and got my private bot working, but I noticed that if I use the **/set** parameter inside the Telegram app in order to modify the feed, then many features are missing compared to the public bot.

Private bot:
![image](https://user-images.githubusercontent.com/53270518/157469374-11ea0433-ebee-4cf5-be7a-2bb5b7eea82f.png)

Public bot:
![image](https://user-images.githubusercontent.com/53270518/157469871-7358080f-b18b-4886-bee6-43030ef6578b.png)

**Comment by Rongronggg9** [comment]
Send `/version` to check if your bot is the latest version.

**Comment by purk4** [comment]
v2.0.0-70-gbd5beeb@master
build@2022-02-28T23:18:15+00:00

I ran the script via docker-compose

**Comment by Rongronggg9** [comment]
Are you using a docker hub mirror? If so, disable any mirrors, or just wait for them to update.
`docker-compose pull && docker-compose up -d` to update to the latest version.

**Comment by purk4** [comment]
Thank you, It is OK now :)
