### ISSUE TITLE
Template feature request

### ISSUE THREAD

**Issue by purk4** [Rongronggg9/RSS-to-Telegram-Bot#49]
Please could you advice on how can I modify the default template to achieve this kind of design:

**Title**
full link (https://.....)
<Link preview>

For examle, I like to use this style:
![image](https://user-images.githubusercontent.com/53270518/157507816-843509e5-3d1a-48ea-829d-2a8c00ff9b1d.png)

I tried several parameters and this is the closest thing that I was able to get:
![image](https://user-images.githubusercontent.com/53270518/157508074-2b8691ec-7a75-4b87-baea-df5b2b6ac83c.png)

**Comment by Rongronggg9** [comment]
May I ask you in what situations this format is useful? Or is it just your personal preference?

> how can I modify the default template to achieve this kind of design

check [`src.parsing.post_formatter.get_post_header_and_footer`](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/src/parsing/post_formatter.py#L274-L403), search for self.link and you know what to do.

For example, replace [`src.parsing.post_formatter.get_post_header_and_footer` (L375)](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/src/parsing/post_formatter.py#L375) 
```py
                title_html = Bold(Underline(Link(title, param=self.link))).get_html()
```
with
```py
                title_html = Text([Bold(title), Br(), Text(self.link)]).get_html()
```

**Comment by purk4** [comment]
Thanks. I will try to modify the code. 

There are very good reason to use full URLs as links, because there are no additional "Open this link?" confirmation box. Each time the user clicks on the link the user also need to click open inside the confirmation box. This is very annoying and inconvenient.

This affects both mobile and desktop version of the Telegram. There are no way to disable this confirmation box other way than use the original full URLs as links.

![image](https://user-images.githubusercontent.com/53270518/157576816-b51bda55-c776-4540-876c-aac454826a44.png)

**Comment by purk4** [comment]
Thank you very much. 
I tested it using Dry Run method and got it working as I liked :)

![image](https://user-images.githubusercontent.com/53270518/157585178-97a6a1b7-8276-412b-b6a8-0f5a80571d67.png)

**Comment by Rongronggg9** [comment]
6bcdd293590ab3ee4604bb25c45f483ce02c829f
done
