### ISSUE TITLE
[Request] Add mongodb Support

### ISSUE THREAD

**Issue by killerlearner** [Rongronggg9/RSS-to-Telegram-Bot#492]
As elephant sql is ending it's services in Jan 2025. I would like to request support for mongodb database.

**Comment by Rongronggg9** [comment]
ElephantSQL is just a PostgreSQL hosting service. Its sunsetting means virtually nothing. PostgreSQL is still powerful and energic and you can always deploy it yourself. Not to mention RSStT also supports SQLite.

[MongoDB database server and tools are licensed under SSPL](https://www.mongodb.com/legal/licensing/community-edition), which is just a source-available license and is ["Not an Open Source License"](https://opensource.org/blog/the-sspl-is-not-an-open-source-license), or MongoDB, Inc.’s commercial license. MongoDB, IMHO, hurts the open-source community and [its removal from Debian, Fedora, RHEL, etc](https://www.zdnet.com/article/mongodb-open-source-server-side-public-license-rejected/) is the best proof. Though most MongoDB drivers are still open-sourced, I have not seen any benefit in supporting it and I am not willing to put my effort into supporting any software that is not really open-sourced.

**Comment by Rongronggg9** [comment]
FYI, RSStT depends on [tortoise-orm](https://tortoise.github.io/) to support both PostgreSQL and SQLite. Only if tortoise-orm gains MongoDB support is there a chance that RSStT gains it too.
