### ISSUE TITLE
[Help] Regarding setup it's format for my liking

### ISSUE THREAD

**Issue by killerlearner** [Rongronggg9/RSS-to-Telegram-Bot#493]
I wanna set it up like this 
![IMG_20240721_110921](https://github.com/user-attachments/assets/042841b0-f1cf-4474-b04e-c1addd87f290)

But it's setting like this 
![IMG_20240721_110906](https://github.com/user-attachments/assets/9695cc17-5264-4dd1-b23b-9df20ec15e20)

So I wanna remove any Symbol from title like <#b> etc 

Paste link below like this, which it isn't doing even after setting bare link below and link preview enable. 

And third if possible I wanna remove from url 
https://www.google.com/url?rct=j&sa=t&url= **realurl** &ct=ga&cd=CAIyHmE4ZjUwMTZlMDQ4ZjUyNDU6Y28uaW46ZW46SU46Ug&usg=AOvVaw2RauLGFucUOlEnqXEpjuN4

**Comment by Rongronggg9** [comment]
> So I wanna remove any Symbol from title like <#b> etc

The item (entry) of the feed contains HTML in its title, which violates the [best practice of RSS](https://www.rssboard.org/rss-profile#data-types-characterdata). But indeed, RSStT needs to sanitize titles before rendering messages.

> Paste link below like this, which it isn't doing even after setting bare link below and link preview enable.

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/dev/docs/formatting-settings.md

> And third if possible I wanna remove from url 
https://www.google.com/url?rct=j&sa=t&url= **realurl** &ct=ga&cd=CAIyHmE4ZjUwMTZlMDQ4ZjUyNDU6Y28uaW46ZW46SU46Ug&usg=AOvVaw2RauLGFucUOlEnqXEpjuN4

No, consult the feed generator to do such a sanitization.
