### ISSUE TITLE
RSS-to-Telegram-Bot 会发送大量不知名域名请求

### ISSUE THREAD

**Issue by Yumega** [Rongronggg9/RSS-to-Telegram-Bot#510]
安装adguardhome 会发现 RSS-to-Telegram-Bot 会持续发送 
www.lankenauta.it
utilisputidiriflessione.blogspot.com

![image](https://github.com/user-attachments/assets/bb8b04c0-e4bd-48bb-8c98-f7db7879e6bd)

这些垃圾域名的请求

**Comment by Rongronggg9** [comment]
@Yumega RSStT 不含有恶意代码，你可自行审计。
这最可能是由于「有人」订阅了上述域名中的 feed。考虑是否未设置 MULTIUSER=0 从而导致任何人均可使用你的 RSStT 实例（参考 FAQ）。你可自行审计数据库以检查是否存在来自他人的活动订阅。亦可通过 DEBUG=1 查看详细日志。
还可能是由于你订阅的 feed 中含有来自上述域名的图片，RSStT 拉取图片（每张图片最多拉取 5KiB 的头部数据）以识别其性质。考虑到你已拦截上述请求，在这种情况下，DEBUG=1 将会导致输出有关于拉取图片失败的日志。

**Comment by Rongronggg9** [comment]
> 这最可能是由于「有人」订阅了上述域名中的 feed。考虑是否未设置 MULTIUSER=0 从而导致任何人均可使用你的 RSStT 实例（参考 FAQ）。你可自行审计数据库以检查是否存在来自他人的活动订阅。亦可通过 DEBUG=1 查看详细日志。

请自行排查。
由于这不是 RSStT 的 bug，且未提供有效信息，将关闭此 issue。
