### ISSUE TITLE
Use Personal Account and not Bot Account

### ISSUE THREAD

**Issue by weskerty** [Rongronggg9/RSS-to-Telegram-Bot#521]
The question is whether I can easily use a personal account as a bot.
Telegram has the limitation that other bots cannot see each other, and with a user account I could bypass that and have projects like Matterbridge forward the RSS to the various platforms.

**Comment by Rongronggg9** [comment]
Probably unfeasible. Only bots accounts are able to send messages with inline buttons. Without that, you would be unable to manage your feeds.

**Comment by weskerty** [comment]
>  unable to manage your subscriptions.

clone the database from a working bot.
Do you know how to make it use a user account?
Or does it require changes to the code?

**Comment by Rongronggg9** [comment]
> does it require changes to the code?

yes

**Comment by weskerty** [comment]
> yes

An alternative solution is to use a channel and thus you can use RSSTT on multiple platforms.

![image](https://github.com/user-attachments/assets/e3dc4414-cd9b-4b81-91e2-35c6c749a9fb)
![image](https://github.com/user-attachments/assets/e018193e-02a3-49ac-935f-849316392d06)
