### ISSUE TITLE
Docker中更新订阅数据无法保留

### ISSUE THREAD

**Issue by imrayyu** [Rongronggg9/RSS-to-Telegram-Bot#529]
大佬您好：

我是在Docker中部署的机器人，当有更新时重新拉取后发现机器人的订阅清单会消失。

我的机器人是在群聊中设置的，更新后/list清单为空。

是否能开发一个保留订阅列表的更新方法呢？

谢谢~

**Comment by Rongronggg9** [comment]
没有任何更新方法需要被开发，一旦目录映射被正确配置，数据库不会灭失。

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/blob/4d3eee7887d64838b25d55a09be935c931676fa9/docker-compose.yml.sample#L9-L10
