### ISSUE TITLE
Invalid Media: Video

### ISSUE THREAD

**Issue by WeissbrotDE** [Rongronggg9/RSS-to-Telegram-Bot#99]
Videos are not downloaded and posted.

**Comment by demosthenez** [comment]
> > Provide Telegram with an HTTP URL for the file to be sent. Telegram will download and send the file. 5 MB max size for photos and **20 MB max for other types of content**.
> 
> https://core.telegram.org/bots/api#sending-files

is there an easy way to reconfigure this for extended file sizes?

**Comment by AuroraDysis** [comment]
@Rongronggg9 I think there is an easy way to solve this problem. For large videos, simply embedding them into Telegraph would work perfectly.
